In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr + 2)
print(arr * 3)
print(arr / 2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print(arr[::-1])

[5 4 6 3 2 1]


In [3]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 5 7 8 9]


In [4]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 1 2]


In [5]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0, 1])
print(arr[2, 0])

20
70


In [6]:
import numpy as np

DeepanjanBaral = np.linspace(10, 100, 25)

print(DeepanjanBaral)
print("Dimensions:", DeepanjanBaral.ndim)
print("Shape:", DeepanjanBaral.shape)
print("Total elements:", DeepanjanBaral.size)
print("Data type:", DeepanjanBaral.dtype)
print("Total bytes:", DeepanjanBaral.nbytes)

transpose = DeepanjanBaral.reshape(25, 1)

print("Transpose:")
print(transpose)

print("Using T attribute:")
print(DeepanjanBaral.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [7]:
transpose = DeepanjanBaral.reshape(25, 1)

In [8]:
import numpy as np

ucs420_DeepanjanBaral = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Mean:", np.mean(ucs420_DeepanjanBaral))
print("Median:", np.median(ucs420_DeepanjanBaral))
print("Maximum:", np.max(ucs420_DeepanjanBaral))
print("Minimum:", np.min(ucs420_DeepanjanBaral))
print("Unique elements:", np.unique(ucs420_DeepanjanBaral))

reshaped_ucs420_DeepanjanBaral = ucs420_DeepanjanBaral.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_DeepanjanBaral)

resized_ucs420_DeepanjanBaral = np.resize(ucs420_DeepanjanBaral, (2, 3))

print("Resized array:")
print(resized_ucs420_DeepanjanBaral)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
