In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

temperature_corrected = temperature + 2

print("Corrected temperatures:", temperature_corrected)

fahrenheit = (9 / 5) * temperature_corrected + 32

print("Fahrenheit:", fahrenheit)

readings_greater_32 = temperature_corrected[temperature_corrected > 32]

print("Readings greater than 32°C:", readings_greater_32)

count = np.sum(temperature_corrected > 32)

print("Number of readings greater than 32°C:", count)

Corrected temperatures: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings greater than 32°C: 5


Vectorization performs operations on the entire NumPy array at once without explicitly iterating through each element, making calculations faster and more efficient. Boolean indexing uses a condition to select only the required elements directly from the array, avoiding manual checking of every value.

In [2]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Total steps:", np.sum(steps))

print("Mean steps:", np.mean(steps))

print("Maximum steps:", np.max(steps))

print("Minimum steps:", np.min(steps))

print("Total steps for each day:", np.sum(steps, axis=0))

print("Total steps for each user:", np.sum(steps, axis=1))

max_index = np.argmax(steps)

print("Index of maximum value:", np.unravel_index(max_index, steps.shape))

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Index of maximum value: (np.int64(3), np.int64(2))


In [3]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]

subset[0] = 999

print("Original:", original)
print("Subset:", subset)

copied_array = original[1:5].copy()

copied_array[0] = 500

print("Original:", original)
print("Copied array:", copied_array)

matrix = np.arange(1, 13).reshape(3, 4)

print("Matrix:")
print(matrix)

print("First row:", matrix[0])

print("Last row:", matrix[-1])

print("Second column:", matrix[:, 1])

print("Rows 1-2 and columns 2-3:")
print(matrix[1:3, 2:4])

flattened_array = matrix.flatten()

ravelled_array = matrix.ravel()

print("Flatten:", flattened_array)

print("Ravel:", ravelled_array)

ravelled_array[0] = 100

print("Matrix after modifying ravel:", matrix)

flattened_array[1] = 200

print("Matrix after modifying flatten:", matrix)

print("Shape:", matrix.shape)

print("Dimensions:", matrix.ndim)

print("Size:", matrix.size)

print("Data type:", matrix.dtype)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix after modifying ravel: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Matrix after modifying flatten: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [4]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)

print("Dimensions of X:", X.ndim)

XT = X.T

print("X.T:")
print(XT)

XTX = X.T @ X

print("X.T @ X:")
print(XTX)

XTX_inverse = np.linalg.inv(XTX)

print("Inverse of X.T @ X:")
print(XTX_inverse)

beta = XTX_inverse @ X.T @ y

print("OLS coefficients:")
print(beta)

new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients:
[-0.15921454  0.14083853 10.06302242]
Predicted assistance score: 75.27862544779117


In [5]:
new_user = np.array([5, 40, 7])