In [1]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


In [2]:
import numpy as np

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

print(array1.flatten())
print(array1.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.array_equal(arr1, arr2))

True


In [4]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
max_count = counts.max()
most_frequent = values[counts == max_count]

print(most_frequent)
print(np.where(x == most_frequent[0])[0])

[1]
[0 5 7 8 9]


In [5]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
max_count = counts.max()
most_frequent = values[counts == max_count]

print(most_frequent)

for value in most_frequent:
    print(np.where(y == value)[0])

[1 3]
[0 1 2]
[4 8 9]


In [6]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print(gfg.sum())
print(gfg.sum(axis=1))
print(gfg.sum(axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [7]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

print(np.trace(n_array))

eigenvalues, eigenvectors = np.linalg.eig(n_array)

print(eigenvalues)
print(eigenvectors)

print(np.linalg.inv(n_array))

print(np.linalg.det(n_array))

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [8]:
import numpy as np

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

print(p @ q)
print(np.cov(p.flatten(), q.flatten()))

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [9]:
import numpy as np

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])

print(p @ q)
print(np.cov(p.flatten(), q.flatten()))

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [10]:
import numpy as np
from itertools import product

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x, y))
print(np.outer(x, y))
print(list(product(x.flatten(), y.flatten())))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[(np.int64(2), np.int64(1)), (np.int64(2), np.int64(5)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(5)), (np.int64(2), np.int64(10)), (np.int64(2), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(5)), (np.int64(3), np.int64(0)), (np.int64(3), np.int64(5)), (np.int64(3), np.int64(10)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(5)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(5)), (np.int64(4), np.int64(10)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(5)), (np.int64(3), np.int64(0)), (np.int64(3), np.int64(5)), (np.int64(3), np.int64(10)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(5)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(5)), (np.int64(2), np.int64(10)), (np.int64(2), np.int64(3)), (np.int6

In [11]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

print(np.abs(array))

print(np.percentile(array, [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis=0))
print(np.percentile(array, [25, 50, 75], axis=1))

print(np.mean(array))
print(np.median(array))
print(np.std(array))

print(np.mean(array, axis=0))
print(np.median(array, axis=0))
print(np.std(array, axis=0))

print(np.mean(array, axis=1))
print(np.median(array, axis=1))
print(np.std(array, axis=1))

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [12]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [13]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [14]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]

print(integer_elements)
print(float_elements)

[1. 2. 3. 2.]
[1.2 2.2]


In [16]:
from PIL import Image
import numpy as np

def img_to_array(path):
    image = Image.open(path)
    img_array = np.array(image)

    if len(img_array.shape) == 3:
        np.savetxt("image_rgb.txt", img_array.reshape(-1, 3), fmt='%d')
    elif len(img_array.shape) == 2:
        np.savetxt("image_grayscale.txt", img_array, fmt='%d')

img_to_array("WIN_20260908_12_15_09_Pro.jpg")

In [17]:
import numpy as np

data = np.loadtxt("image_rgb.txt")

print(data)

[[152. 145. 163.]
 [148. 144. 161.]
 [157. 153. 168.]
 ...
 [107. 114. 120.]
 [113. 120. 126.]
 [116. 123. 129.]]
